export const appointmentDetail = [
  {
    id: 1,
    appointmentStatus: 'Upcoming',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Video Call',
    price: 60,
    description: 'Video call with doctor',
    iconAntDesign: 'videocamera',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  },
  {
    id: 2,
    appointmentStatus: 'Upcoming',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Phone Call',
    price: 60,
    description: 'Phone call with doctor',
    iconAntDesign: 'phone',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  },
  {
    id: 3,
    appointmentStatus: 'Upcoming',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Message',
    price: 60,
    description: 'Message with doctor',
    iconAntDesign: 'message1',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  },
  {
    id: 4,
    appointmentStatus: 'Completed',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Video Call',
    price: 60,
    description: 'Video call with doctor',
    iconAntDesign: 'videocamera',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  },
  {
    id: 5,
    appointmentStatus: 'Completed',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Phone Call',
    price: 60,
    description: 'Phone call with doctor',
    iconAntDesign: 'phone',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  },
  {
    id: 6,
    appointmentStatus: 'Completed',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Message',
    price: 60,
    description: 'Message with doctor',
    iconAntDesign: 'message1',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  },
  {
    id: 7,
    appointmentStatus: 'Cancelled',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Video Call',
    price: 60,
    description: 'Video call with doctor',
    iconAntDesign: 'videocamera',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  },
  {
    id: 8,
    appointmentStatus: 'Cancelled',
    name: 'Dr. John Doe',
    speciality: 'Cardiologist',
    hospital: 'St. Mary Hospital',
    rating: 4.5,
    review: 17,
    method: 'Phone Call',
    price: 60,
    description: 'Phone call with doctor',
    iconAntDesign: 'phone',
    date: '11/11/2020',
    time: '10:00 AM',
    duration: '30 minutes',
    patientFullName: 'Andrew Ainsley',
    patientGender: 'Male',
    patientAge: 27,
    patientProblem: 'Lorem ipsum dolor sit amet'
  }
]
